### PR TITLE
refactor: use Bandcamp private API

### PR DESCRIPTION
**Pull request by masterT**
Refactor the package with TypeScript and use Bandcamp private API instead of scraping since this is more stable. 

Fixes:
- #62
- - ...

### CODE REVIEW

**Comment by drone1** [comment]
Hey @masterT. 

When you refer to "private API" are you referring to [this](https://bandcamp.com/developer#calling_the_api), or is there some other API? I don't see functionality beyond the scope of accessing one's own label or sales data.

Either way, using a private API would mean users of bandcamp-scraper is no longer a scraper. It's a wrapper at that point, and that sounds like a different package. One would presumably need be granted API key, and if you get one, Bandcamp can decide to turn off the faucet at any point, whereas of course with a scraper, one can legally, anonymously gather public data from a site. I personally only make a few requests here and there, but I certainly appreciate the punk nature of scraping over gatekeeped private API calls. 

It sounds like the issue is stability, which I can understand, but doesn't Bandcamp only update their site once every 17 years anyway? :)

**Comment by masterT** [comment]
@drone1 You are probably right, that it might be a different package. I was referring to using the private API Bandcamp is using in their mobile application. Since you can use the application without being authenticated the endpoints are publicly available. 

The difficulty with scraping is maintaining the code.

**Comment by masterT** [comment]
@drone1 You are probably right, that it might be a different package. I was referring to using the private API Bandcamp is using in their mobile application. Since you can use the application without being authenticated the endpoints are publicly available. 

The difficulty with scraping is maintaining the code.

**Comment by drone1** [comment]
> @drone1 You are probably right, that it might be a different package. I was referring to using the private API Bandcamp is using in their mobile application. Since you can use the application without being authenticated the endpoints are publicly available.
> 
> The difficulty with scraping is maintaining the code.

Got it. OK, but would that be against their terms of service? And if not, at any point they could decide to adjust their terms of service such that one would be in violation for accessing those API‘s. I do understand that it must be a pain to maintain this package since it is a scraper, but at least it is legal no matter what, as far as I understand. I recommend caution. :)

**Comment by masterT** [comment]
Scraping is a gray zone too. You convinced me not to use their private API in this package. I will still do a refactor in TypeScript (JavaScript) since the code base is a mess.

Thank you for your input. 😊

**Pull request closed without merging**
