### PR TITLE
Add support for labels

### PR DESCRIPTION
**Pull request by pierluigi**
Fixes https://github.com/masterT/bandcamp-scraper/issues/40

### CODE REVIEW

**Comment by masterT** [comment]
Nice, there are some things missing. Can you add the documentation for this function in the `README.md` and add a test?

**Comment by pierluigi** [comment]
@masterT ready for a second review! Apologies for the stylistic changes courtesy of prettier.

**Comment by masterT** [comment]
Thank you for the PR, I'll merge and cleanup since I removed the spec using fixture. 😄

**Comment by masterT** [comment]
Version `bandcamp-scraper@1.3.0` released. 🎉

**Pull request merged**
